export const bearingsRowData = [
    {
        refClause: "",
        description: "L10 life:",
        purchaserReq: "select",
        purchaserReqUOM: "hours",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "hours",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Drive end (DE) bearing number:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Non-drive end (NDE) bearing number:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "External radial loading on motor shaft end:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "External axial loading on motor shaft end:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Recommended lubricant:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "  Grease:",
        purchaserReq: "input data",
        purchaserReqUOM: "A",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "A",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "  Oil mist lubricant:",
        purchaserReq: "input data",
        purchaserReqUOM: "A",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "A",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Sealed for life anti-friction bearing:",
        purchaserReq: "not required",
        purchaserReqUOM: "",
        supplierOfferedVal: "not required",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "ASD fed motor - non-drive end (NDE) insulation bearing requirement:",
        purchaserReq: "required",
        purchaserReqUOM: "",
        supplierOfferedVal: "required",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
