export const instrumentationRowData = [
    {
        refClause: "",
        description: "Provisions for vibration monitoring:",
        purchaserReq: "not required",
        purchaserReqUOM: "",
        supplierOfferedVal: "not required",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Winding temperature detectors:",
        purchaserReq: "not required",
        purchaserReqUOM: "",
        supplierOfferedVal: "not required",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Bearing temperature detectors:",
        purchaserReq: "not required",
        purchaserReqUOM: "",
        supplierOfferedVal: "not required",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Instrumentation terminal box:",
        purchaserReq: "not required",
        purchaserReqUOM: "",
        supplierOfferedVal: "not required",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Provision for IoT hardware installation:",
        purchaserReq: "not required",
        purchaserReqUOM: "",
        supplierOfferedVal: "not required",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "  Motor monitoring device (IoT):",
        purchaserReq: "not required",
        purchaserReqUOM: "",
        supplierOfferedVal: "not required",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
