export const mailTerminalBoxRowData = [
    {
        refClause: "",
        description: "Position:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Ingress protection of terminal boxes:",
        purchaserReq: "IP55",
        purchaserReqUOM: "",
        supplierOfferedVal: "IP55",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Main terminal box cable entry hole size and number:",
        purchaserReq: "as per NEMA MG1 Part 4",
        purchaserReqUOM: "",
        supplierOfferedVal: "as per NEMA MG1 Part 4",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Oversized terminal box:",
        purchaserReq: "not required",
        purchaserReqUOM: "",
        supplierOfferedVal: "not required",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Main terminal box material:",
        purchaserReq: "cast iron",
        purchaserReqUOM: "",
        supplierOfferedVal: "cast iron",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
