export const motorConstructionRowData = [
    {
        refClause: "",
        description: "Motor weight:",
        purchaserReq: "input data",
        purchaserReqUOM: "select",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "select",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Stainless steel hardware:",
        purchaserReq: "not required",
        purchaserReqUOM: "",
        supplierOfferedVal: "not required",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Enclosure type:",
        purchaserReq: "TEFC",
        purchaserReqUOM: "",
        supplierOfferedVal: "TEFC",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Enclosure ingress protection:",
        purchaserReq: "IP55",
        purchaserReqUOM: "",
        supplierOfferedVal: "IP55",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
