export const siteConditionsLocationEnvironmentRowData = [
    {
        refClause: "",
        description: "Floating/marine/shipboard:",
        purchaserReq: "not applicable",
        purchaserReqUOM: "",
        supplierOfferedVal: "not applicable",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Chemicals or corrosives:",
        purchaserReq: "input data",
        purchaserReqUOM: "",
        supplierOfferedVal: "input data",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Altitude:",
        purchaserReq: "select",
        purchaserReqUOM: "m (ft)",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "m (ft)",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Minimum ambient air temperature:",
        purchaserReq: "select",
        purchaserReqUOM: "°C (°F)",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "°C (°F)",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "Maximum ambient air temperature:",
        purchaserReq: "select",
        purchaserReqUOM: "°C (°F)",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "°C (°F)",
        additionalNotes: "",
    },
]
