export const spaceHeatersRowData = [
    {
        refClause: "",
        description: "Space heater:",
        purchaserReq: "not required",
        purchaserReqUOM: "",
        supplierOfferedVal: "not required",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "  Space heater terminal box:",
        purchaserReq: "not required",
        purchaserReqUOM: "",
        supplierOfferedVal: "not required",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "  Space heater voltage:",
        purchaserReq: "select",
        purchaserReqUOM: "V AC",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "V AC",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "  Warning label:",
        purchaserReq: "select",
        purchaserReqUOM: "",
        supplierOfferedVal: "select",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
    {
        refClause: "",
        description: "    Warning label language:",
        purchaserReq: "English",
        purchaserReqUOM: "",
        supplierOfferedVal: "English",
        supplierOfferedValUOM: "",
        additionalNotes: "",
    },
]
