name: Build
on:
  workflow_call:

env:
  ARTIFACT_NAME: spinedatasheet.zip
  NODE_VERSION: '18'

jobs:
  build:
    name: '🛠️ Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: export NODE_ENV=production && yarn build


      - name: 'Upload artifact'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: out/${{ env.ARTIFACT_NAME }}
          retention-days: 7