name: 🚀 Push
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force:
        description: "Force deploy to prod"
        type: boolean
        default: false
        required: true

env:
  FUSION_APP_KEY: spinedatasheet
  NODE_VERSION: ${{ '16' }}

jobs:
  build:
    name: Build
    uses: equinor/spinedatasheetweb/.github/workflows/build.yml@cicd
    
  release_please:
    name: 🔖 Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: spinedatasheet
          changelog-types: >
            [{"type":"feat","section":"Features","hidden":false},
            {"type":"fix","section":"Bug Fixes","hidden":false},
            {"type":"style", "section":"Cosmetic changes","hidden":false},
            {"type":"docs","section":"For developers","hidden":false},
            {"type":"refactor","section":"For developers","hidden":false},
            {"type":"ci", "section":"For developers","hidden":false},
            {"type":"chore", "section":"For developers","hidden":false},
            {"type":"perf", "section":"Optimalization","hidden":false}]
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    
  deploy-ci:
    name: '🚀 CI'
    runs-on: ubuntu-latest
    needs: build
    environment: CI
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.FUSION_APP_KEY }}.zip

      - name: Deploy to Fusion Portal
        uses: equinor/farfetched-actions/fusion-deploy@v2.0
        with:
          fusion-portal-url: ${{ vars.FUSION_PORTAL_URL }}
          app-key: ${{ env.FUSION_APP_KEY }}
          artifact-path: ${{ env.FUSION_APP_KEY }}.zip
          azure-resource-id: ${{ vars.FUSION_RESOURCE_ID }}
          azure-tenant-id: ${{ vars.AZURE_TENANT_ID }}
          azure-client-id: ${{ vars.AZURE_SERVICE_PRINCIPAL_CLIENT_ID }}
          
  deploy_qa:
    name: '🚀 QA'
    runs-on: ubuntu-latest
    needs: [release_please, deploy-ci]
    if: ${{ needs.release_please.outputs.release_created || inputs.force }}
    environment: QA
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.FUSION_APP_KEY }}.zip

      - name: Deploy to Fusion Portal
        uses: equinor/farfetched-actions/fusion-deploy@v2.0
        with:
          fusion-portal-url: ${{ vars.FUSION_PORTAL_URL }}
          app-key: ${{ env.FUSION_APP_KEY }}
          artifact-path: ${{ env.FUSION_APP_KEY }}.zip
          azure-resource-id: ${{ vars.FUSION_RESOURCE_ID }}
          azure-tenant-id: ${{ vars.AZURE_TENANT_ID }}
          azure-client-id: ${{ vars.AZURE_SERVICE_PRINCIPAL_CLIENT_ID }}

  deploy_prod:
    name: '🚀 Prod'
    runs-on: ubuntu-latest
    needs: [deploy_qa]
    environment: PROD
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.FUSION_APP_KEY }}.zip

      - name: Deploy to Fusion Portal
        uses: equinor/farfetched-actions/fusion-deploy@v2.0
        with:
          fusion-portal-url: ${{ vars.FUSION_PORTAL_URL }}
          app-key: ${{ env.FUSION_APP_KEY }}
          artifact-path: ${{ env.FUSION_APP_KEY }}.zip
          azure-resource-id: ${{ vars.FUSION_RESOURCE_ID }}
          azure-tenant-id: ${{ vars.AZURE_TENANT_ID }}
          azure-client-id: ${{ vars.AZURE_SERVICE_PRINCIPAL_CLIENT_ID }}
